// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl2J8V5D_XQz_5Yisu-Lw2e6rnkh50cts',
    appId: '1:231298642777:web:ab0c6bd590b7d8f8e6d248',
    messagingSenderId: '231298642777',
    projectId: 'chatapp-fc713',
    authDomain: 'chatapp-fc713.firebaseapp.com',
    storageBucket: 'chatapp-fc713.firebasestorage.app',
    measurementId: 'G-2LJ99KLN2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmTcWl7BabBdueSjAZUowqYsPttnZq6AQ',
    appId: '1:231298642777:android:0285ab668d345a65e6d248',
    messagingSenderId: '231298642777',
    projectId: 'chatapp-fc713',
    storageBucket: 'chatapp-fc713.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcsgnVSkBQ0CcHsgdNI01sMKjnSLNaCTY',
    appId: '1:231298642777:ios:a1e719650305aa95e6d248',
    messagingSenderId: '231298642777',
    projectId: 'chatapp-fc713',
    storageBucket: 'chatapp-fc713.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcsgnVSkBQ0CcHsgdNI01sMKjnSLNaCTY',
    appId: '1:231298642777:ios:a1e719650305aa95e6d248',
    messagingSenderId: '231298642777',
    projectId: 'chatapp-fc713',
    storageBucket: 'chatapp-fc713.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl2J8V5D_XQz_5Yisu-Lw2e6rnkh50cts',
    appId: '1:231298642777:web:a82e3a8a084664f8e6d248',
    messagingSenderId: '231298642777',
    projectId: 'chatapp-fc713',
    authDomain: 'chatapp-fc713.firebaseapp.com',
    storageBucket: 'chatapp-fc713.firebasestorage.app',
    measurementId: 'G-LHW01B0HLH',
  );
}
